[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

log = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }

reqwest = { workspace = true, features = ["json"] }

ewebsock = "0.8.0"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }

iced = { workspace = true, features = ["tokio", "sipper"] }

async-tungstenite = { version = "0.34", features = [
    "tokio-rustls-webpki-roots",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced = { workspace = true, features = ["sipper", "webgl", "fira-sans"] }
