[package]
name = "profile-server"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
server-shared = { path = "../server-shared" }

log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

sqlx = { workspace = true, features = [
    "postgres",
    "macros",
    "runtime-tokio",
    "time",
] }
tokio = { workspace = true, features = ["full"] }
warp = { workspace = true, features = ["server"] }
axum = { workspace = true }
